//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 06:25:13 PM CEST 
//


package fr.inria.cominlabs.activityreport.haldb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.inria.cominlabs.activityreport.haldb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.inria.cominlabs.activityreport.haldb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Documents.Typdoc.Document.Authors.Author }
     * 
     */
    public Documents.Typdoc.Document.Authors.Author createDocumentsTypdocDocumentAuthorsAuthor() {
        return new Documents.Typdoc.Document.Authors.Author();
    }

    /**
     * Create an instance of {@link Documents.Typdoc.Document.Authors.Author.Affiliations.Affiliation.Tutelles }
     * 
     */
    public Documents.Typdoc.Document.Authors.Author.Affiliations.Affiliation.Tutelles createDocumentsTypdocDocumentAuthorsAuthorAffiliationsAffiliationTutelles() {
        return new Documents.Typdoc.Document.Authors.Author.Affiliations.Affiliation.Tutelles();
    }

    /**
     * Create an instance of {@link Documents.Typdoc.Document.Authors.Author.Affiliations.Affiliation }
     * 
     */
    public Documents.Typdoc.Document.Authors.Author.Affiliations.Affiliation createDocumentsTypdocDocumentAuthorsAuthorAffiliationsAffiliation() {
        return new Documents.Typdoc.Document.Authors.Author.Affiliations.Affiliation();
    }

    /**
     * Create an instance of {@link Documents.Typdoc.Document.Authors }
     * 
     */
    public Documents.Typdoc.Document.Authors createDocumentsTypdocDocumentAuthors() {
        return new Documents.Typdoc.Document.Authors();
    }

    /**
     * Create an instance of {@link Documents.Typdoc }
     * 
     */
    public Documents.Typdoc createDocumentsTypdoc() {
        return new Documents.Typdoc();
    }

    /**
     * Create an instance of {@link Documents }
     * 
     */
    public Documents createDocuments() {
        return new Documents();
    }

    /**
     * Create an instance of {@link Documents.Typdoc.Document.FilesUrl }
     * 
     */
    public Documents.Typdoc.Document.FilesUrl createDocumentsTypdocDocumentFilesUrl() {
        return new Documents.Typdoc.Document.FilesUrl();
    }

    /**
     * Create an instance of {@link Documents.Typdoc.Document.Authors.Author.Affiliations }
     * 
     */
    public Documents.Typdoc.Document.Authors.Author.Affiliations createDocumentsTypdocDocumentAuthorsAuthorAffiliations() {
        return new Documents.Typdoc.Document.Authors.Author.Affiliations();
    }

    /**
     * Create an instance of {@link Documents.Typdoc.Document }
     * 
     */
    public Documents.Typdoc.Document createDocumentsTypdocDocument() {
        return new Documents.Typdoc.Document();
    }

}
